# Generated by Django 3.2.5 on 2021-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('h1', models.PositiveIntegerField()),
                ('h2', models.PositiveIntegerField()),
                ('h3', models.PositiveIntegerField()),
                ('a', models.TextField()),
            ],
        ),
    ]
