# Generated by Django 3.2.5 on 2021-07-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='a',
            field=models.TextField(blank=True),
        ),
    ]
